# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageCode = "cn"
languageContent = "content/"
languageName = "简体中文"
languagedirection = "ltr"
title = "简记"
weight = 1
[zh-cn.params]
sidebar.subtitle = "识盈虚之有数，觉宇宙之无穷。"

[en]
languageCode = "en"
languageContent = "content/"
languageName = "English"
languagedirection = "ltr"
title = "Notes"
weight = 2
[en.params]
sidebar.subtitle = "Grasp the finite cycles of existence and sense the infinite expanse of the cosmos."

