# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Notes"
weight = 1
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "简记"
weight = 2
